//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityExam.Entityframework
{
    using System;
    using System.Collections.Generic;
    
    public partial class EducationDetail
    {
        public int EductaionId { get; set; }
        public Nullable<int> EmployeeId { get; set; }
        public string Qualification { get; set; }
        public string SchoolName { get; set; }
        public string Colloge_UnivercityName { get; set; }
        public Nullable<int> PassOutYear { get; set; }
        public string Subject_Field { get; set; }
        public string Percentage_Grade { get; set; }
        public Nullable<bool> IsActive { get; set; }
    }
}
