//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityExam.Entityframework
{
    using System;
    using System.Collections.Generic;
    
    public partial class opal
    {
        public int Empid { get; set; }
        public Nullable<decimal> BasicSalary { get; set; }
        public Nullable<decimal> HouseRent { get; set; }
        public Nullable<decimal> Transportallowance { get; set; }
        public Nullable<decimal> MedicalAllowance { get; set; }
        public Nullable<decimal> PF { get; set; }
        public Nullable<decimal> Tax { get; set; }
        public Nullable<bool> IsActive { get; set; }
    }
}
