//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityExam.Entityframework
{
    using System;
    using System.Collections.Generic;
    
    public partial class SubCastMaster
    {
        public int SubCastId { get; set; }
        public Nullable<int> CastId { get; set; }
        public string SubCastName { get; set; }
        public Nullable<bool> IsActive { get; set; }
    }
}
